development:
  adapter: postgresql
  encoding: unicode
  database: mydevdb
  pool: 5
  username: myuser
  password: mypass

test:
  adapter: postgresql
  encoding: unicode
  database: mytestdb
  pool: 5
  username: myuser
  password: mypass

