development:
  adapter: postgresql
  encoding: unicode
  database: fagin
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: fagin
  pool: 5
  username:
  password:

